<?php
// =============================================================================
// Moodle 5.x config.php template
// Generated by MoodleKit — do not edit manually
// Regenerate: moodlekit site create {{SLUG}} --reconfigure
// =============================================================================

unset($CFG);
global $CFG;
$CFG = new stdClass();

// ── Database ──────────────────────────────────────────────────────────────
$CFG->dbtype    = '{{DB_TYPE}}';    // pgsql | mariadb | mysqli
$CFG->dblibrary = 'native';
$CFG->dbhost    = '127.0.0.1';
$CFG->dbname    = '{{DB_NAME}}';
$CFG->dbuser    = '{{DB_USER}}';
$CFG->dbpass    = '{{DB_PASS}}';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = [
    'dbpersist' => 0,
    'dbport'    => '{{DB_PORT}}',
    'dbsocket'  => '',
];

// ── Site ──────────────────────────────────────────────────────────────────
$CFG->wwwroot   = 'https://{{DOMAIN}}';
$CFG->dataroot  = '{{MOODLEDATA_DIR}}';
$CFG->admin     = 'admin';
$CFG->directorypermissions = 02777;

// ── Moodle 5.x Router (required for r.php front controller) ───────────────
$CFG->routerconfigured = true;

// ── X-Accel-Redirect (Nginx internal redirect for file serving) ───────────
$CFG->xsendfile        = 'X-Accel-Redirect';
$CFG->xsendfilealiases = [
    '/dataroot/' => $CFG->dataroot,
];

// ── SSL Proxy (set true if behind a reverse proxy/load balancer) ──────────
$CFG->sslproxy = false;

// ── Cron ─────────────────────────────────────────────────────────────────
$CFG->cronclionly = true;
$CFG->cronremotepassword = '';

// ── Performance ───────────────────────────────────────────────────────────
$CFG->pathtophp = '/usr/bin/php{{PHP_VERSION}}';

{{CACHE_CONFIG}}

require_once(__DIR__ . '/lib/setup.php');
