<?php
// =============================================================================
// Moodle 4.x config.php template
// Generated by MoodleKit — do not edit manually
// =============================================================================

unset($CFG);
global $CFG;
$CFG = new stdClass();

// ── Database ──────────────────────────────────────────────────────────────
$CFG->dbtype    = 'mysqli';    // pgsql | mariadb | mysqli
$CFG->dblibrary = 'native';
$CFG->dbhost    = '127.0.0.1';
$CFG->dbname    = 'a';
$CFG->dbuser    = 'b';
$CFG->dbpass    = 'c';
$CFG->prefix    = 'mdl_';
$CFG->dboptions = [
    'dbpersist' => 0,
    'dbport'    => '3306',
    'dbsocket'  => '',
];

// ── Site ──────────────────────────────────────────────────────────────────
$CFG->wwwroot   = 'https://d';
$CFG->dataroot  = 'e';
$CFG->admin     = 'admin';
$CFG->directorypermissions = 02777;

// ── X-Accel-Redirect ──────────────────────────────────────────────────────
$CFG->xsendfile        = 'X-Accel-Redirect';
$CFG->xsendfilealiases = [
    '/dataroot/' => $CFG->dataroot,
];

// ── SSL Proxy ─────────────────────────────────────────────────────────────
$CFG->sslproxy = false;

// ── Cron ──────────────────────────────────────────────────────────────────
$CFG->cronclionly = true;
$CFG->pathtophp   = '/usr/bin/php8.3';


// ── Redis Session Handler ─────────────────────────────────────────────────
$CFG->session_handler_class = '\core\session\redis';
$CFG->session_redis_host    = '127.0.0.1';


require_once(__DIR__ . '/lib/setup.php');
